server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /auth/ {
        proxy_pass http://leave-backend-svc:8000/auth/;
    }

    location /leaves/ {
        proxy_pass http://leave-backend-svc:8000/leaves/;
    }

    location /manager/ {
        proxy_pass http://leave-backend-svc:8000/manager/;
    }

    location /admin/ {
        proxy_pass http://leave-backend-svc:8000/admin/;
    }

    location /chatbot/ {
        proxy_pass http://leave-ai-svc:5000/chatbot/;
    }

    location / {
        try_files $uri /index.html;
    }
}
