version: '3.8'
services:
  frontend: 
    build: ./frontend 
    ports:
      - "3000:80"   # use 3000:3000 if running npm start
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000

  backend: 
    build: ./backend 
    ports:
      - "8000:8000"
    environment: 
      - DB_HOST=host.docker.internal   # works with Oracle XE on Windows host
      - DB_PORT=1521 
      - DB_SERVICE=XEPDB1 
      - DB_USER=leave_app 
      - DB_PASSWORD=leave123 
      - SECRET_KEY=mysecretkey123 
      - ALGORITHM=HS256 
      - ACCESS_TOKEN_EXPIRE_MINUTES=480

  ai-service: 
    build: ./ai-service 
    ports:
      - "5000:5000"
    environment: 
      - DB_DSN=host.docker.internal:1521/XEPDB1
      - DB_USER=leave_app 
      - DB_PASSWORD=leave123 
      - GROQ_API_KEY=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
